import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ScaleProvider } from "../components/ScaleContainer/ScaleProvider";
import "@fontsource/poppins";
import "@fontsource/inter";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MAX_WIDTH = 1920;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ScaleProvider maxWidth={MAX_WIDTH}>{children}</ScaleProvider>
      </body>
    </html>
  );
}
